<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('dist_orders', function (Blueprint $table) {
            $table->id();
            $table->string('order_number')->unique(); // Replaces legacy order_group
            $table->foreignId('franchisee_id')->constrained('franchisees');
            $table->foreignId('user_id')->constrained('users'); // Who placed it
            
            // Workflow Status matching legacy: 0=Pending, 1=Accepted(Billed), 2=Rejected, 3=Dispatched, 4=Delivered
            $table->enum('status', ['pending', 'accepted', 'dispatched', 'delivered', 'rejected', 'cancelled'])->default('pending');
            
            // Financials
            $table->decimal('subtotal', 15, 2)->default(0);
            $table->decimal('discount_amount', 15, 2)->default(0);
            $table->decimal('sgst_amount', 15, 2)->default(0);
            $table->decimal('cgst_amount', 15, 2)->default(0);
            $table->decimal('igst_amount', 15, 2)->default(0);
            $table->decimal('round_off', 8, 2)->default(0);
            $table->decimal('total_amount', 15, 2)->default(0);
            
            // Dispatch and Tracking details from legacy ordereraccept_order
            $table->date('dispatch_date')->nullable();
            $table->string('courier_name')->nullable();
            $table->string('tracking_number')->nullable();
            $table->string('tracking_link')->nullable();
            $table->string('invoice_number')->nullable();
            $table->string('ebill_number')->nullable();
            
            // Approvals and Tracking
            $table->foreignId('accepted_by')->nullable()->constrained('users');
            $table->timestamp('accepted_at')->nullable();
            $table->foreignId('dispatched_by')->nullable()->constrained('users');
            $table->timestamp('dispatched_at')->nullable();
            
            $table->text('notes')->nullable();
            $table->text('rejection_reason')->nullable();

            // Total Commission dynamically generated by the recursive logic
            $table->decimal('total_commission', 15, 2)->default(0);

            $table->timestamps();
            $table->softDeletes();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('dist_orders');
    }
};
